export const moduleQuestions = {
  'logical-mathematical': [
    {
      id: 'lm-1',
      question: 'How many triangles can you see in this pattern? (visualize a hexagon divided into triangles)',
      options: ['6', '8', '9', '12'],
      correct: 9,
      explanation: 'A hexagon divided in a certain way creates 9 triangles when you count all sizes.',
    },
    {
      id: 'lm-2',
      question: 'What is the next number in this sequence? 2, 6, 12, 20, 30...',
      options: ['40', '42', '45', '50'],
      correct: 42,
      explanation: 'Each number is n*(n+1) where n increases: 1*2=2, 2*3=6, 3*4=12, 4*5=20, 5*6=30, 6*7=42',
    },
    {
      id: 'lm-3',
      question: 'If it takes 5 machines 5 minutes to make 5 products, how long would it take 100 machines to make 100 products?',
      options: ['1 minute', '5 minutes', '20 minutes', '100 minutes'],
      correct: 5,
      explanation: 'Each machine makes one product in 5 minutes. 100 machines can make 100 products simultaneously in 5 minutes.',
    },
  ],
  linguistic: [
    {
      id: 'lin-1',
      question: 'What is the opposite of "ephemeral"?',
      options: ['temporary', 'permanent', 'short-lived', 'fleeting'],
      correct: 'permanent',
      explanation: 'Ephemeral means lasting a very short time. Permanent is its opposite.',
    },
    {
      id: 'lin-2',
      question: 'Which sentence has correct grammar?',
      options: [
        'Neither of the students have finished their homework',
        'Neither of the students has finished their homework',
        'Neither of the students having finished their homework',
        'Neither of the students finished their homeworks',
      ],
      correct: 'Neither of the students has finished their homework',
      explanation: '"Neither" is singular, so it takes the singular verb "has", not "have".',
    },
    {
      id: 'lin-3',
      question: 'What literary device is "the sun danced on the water"?',
      options: ['Metaphor', 'Personification', 'Alliteration', 'Simile'],
      correct: 'Personification',
      explanation: 'Personification gives human qualities to non-human things. The sun is described as "dancing".',
    },
  ],
  spatial: [
    {
      id: 'sp-1',
      question: 'If you unfold a cube, how many faces would you see?',
      options: ['4', '5', '6', '8'],
      correct: 6,
      explanation: 'A cube has 6 faces. When unfolded (net), all 6 faces are visible.',
    },
    {
      id: 'sp-2',
      question: 'Rotate this shape 180 degrees clockwise. Which image matches the result? (imagine a triangle pointing right)',
      options: ['Triangle pointing left', 'Triangle pointing up', 'Triangle pointing right', 'Triangle pointing down'],
      correct: 'Triangle pointing left',
      explanation: 'A 180-degree rotation flips the shape both horizontally and vertically.',
    },
    {
      id: 'sp-3',
      question: 'How many blocks are in this 3D structure? (imagine a pyramid: 3 base, 2 middle, 1 top)',
      options: ['4', '5', '6', '7'],
      correct: 6,
      explanation: 'A pyramid structure has 3+2+1 = 6 blocks total.',
    },
  ],
  musical: [
    {
      id: 'mus-1',
      question: 'How many strings does a standard violin have?',
      options: ['3', '4', '5', '6'],
      correct: 4,
      explanation: 'A standard violin has 4 strings: G, D, A, and E.',
    },
    {
      id: 'mus-2',
      question: 'In music, what does "forte" mean?',
      options: ['Fast', 'Loud', 'Slow', 'Soft'],
      correct: 'Loud',
      explanation: 'Forte (f) means to play loudly. The opposite is "piano" which means soft.',
    },
    {
      id: 'mus-3',
      question: 'Which note comes after G in the musical scale?',
      options: ['F', 'A', 'C', 'B'],
      correct: 'A',
      explanation: 'The musical scale is C, D, E, F, G, A, B, C. A comes after G.',
    },
  ],
  'body-kinesthetic': [
    {
      id: 'bk-1',
      question: 'Which sport requires the most balance?',
      options: ['Basketball', 'Tightrope walking', 'Soccer', 'Tennis'],
      correct: 'Tightrope walking',
      explanation: 'Tightrope walking demands precise balance on a narrow surface.',
    },
    {
      id: 'bk-2',
      question: 'What is the primary muscle used in a bicep curl?',
      options: ['Triceps', 'Biceps', 'Deltoids', 'Pectorals'],
      correct: 'Biceps',
      explanation: 'The biceps brachii is the main muscle contracted during a bicep curl.',
    },
    {
      id: 'bk-3',
      question: 'In dance, what does "plié" refer to?',
      options: ['A jump', 'A bend of the knees', 'A turn', 'A leap'],
      correct: 'A bend of the knees',
      explanation: 'Plié is a fundamental ballet movement involving a bending of the knees.',
    },
  ],
  naturalistic: [
    {
      id: 'nat-1',
      question: 'How many legs does an insect have?',
      options: ['4', '6', '8', '10'],
      correct: 6,
      explanation: 'Insects have 6 legs, which is a defining characteristic of the class Insecta.',
    },
    {
      id: 'nat-2',
      question: 'Which of these is a deciduous tree?',
      options: ['Pine', 'Oak', 'Spruce', 'Fir'],
      correct: 'Oak',
      explanation: 'Oak trees lose their leaves in fall. Pines, spruces, and firs are evergreens.',
    },
    {
      id: 'nat-3',
      question: 'In which season do most animals hibernate?',
      options: ['Spring', 'Summer', 'Fall', 'Winter'],
      correct: 'Winter',
      explanation: 'Animals hibernate during winter when food is scarce and temperatures are cold.',
    },
  ],
  intrapersonal: [
    {
      id: 'int-1',
      question: 'What helps you best understand your emotions?',
      options: ['Ignoring them', 'Journaling and reflection', 'Talking constantly', 'Staying busy'],
      correct: 'Journaling and reflection',
      explanation: 'Self-reflection and journaling are key tools for understanding your emotions.',
    },
    {
      id: 'int-2',
      question: 'How do you typically respond to failure?',
      options: ['Blame others', 'Learn from it', 'Give up', 'Deny it happened'],
      correct: 'Learn from it',
      explanation: 'A healthy response to failure is to reflect and extract lessons for growth.',
    },
    {
      id: 'int-3',
      question: 'What is self-awareness most closely related to?',
      options: ['Being alone', 'Understanding your values and beliefs', 'Social skills', 'Physical fitness'],
      correct: 'Understanding your values and beliefs',
      explanation: 'Self-awareness involves knowing your values, beliefs, strengths, and weaknesses.',
    },
  ],
  interpersonal: [
    {
      id: 'inter-1',
      question: 'What is the best way to handle a conflict with a friend?',
      options: ['Avoid them', 'Communicate openly and listen', 'Demand an apology', 'Involve others'],
      correct: 'Communicate openly and listen',
      explanation: 'Open communication and active listening are key to resolving conflicts.',
    },
    {
      id: 'inter-2',
      question: 'How many types of emotions are generally recognized?',
      options: ['3', '5', '7', '10'],
      correct: 7,
      explanation: 'Research often identifies 7 basic emotions: happiness, sadness, fear, anger, surprise, disgust, and contempt.',
    },
    {
      id: 'inter-3',
      question: 'What is empathy?',
      options: [
        'Feeling sorry for someone',
        'Understanding and sharing someone\'s feelings',
        'Being nice to everyone',
        'Giving advice',
      ],
      correct: 'Understanding and sharing someone\'s feelings',
      explanation: 'Empathy is the ability to understand and share the feelings of another person.',
    },
  ],
}
